name: AntiFarm
description: Stops autofarming of Cactus.
version: 1.2
main: info.radthorne.kukelekuuk00.AntiFarm.AntiFarm
author: Kukelekuuk00
website: http://dev.bukkit.org/server-mods/cactus-autofarming-fix/


commands:
   afcactus:
      description: Toggles AntiFarm cactus on/off
      usage: /<command>
      permission: <plugin name>.afcactus
      permission-message: You don't have permission to do this.